var GAME_LEVELS = [
  ["                                                                                ",
   "                           xxxxxx            f                                  ",
   "                           x!!!!x        o o o o o o           o y o            ",
   "                           x!!!!x        xxxxxxxxxxxxxx     xxxxxxxxxxx         ",
   "                            v  v                      x!!!!!x         xx        ",
   "                                                      x!!!!!x                   ",
   "                                                      xxxxxxx             xx    ",
   "               o o    y                                                         ",
   "                      y            o o                                xx        ",
   "              xxxxxxxxxxxxxx                                                    ",
   "                           x    xxxxxxx           y                       xx    ",
   "         y          o      x!!!!x      x    o    xxxx   xxxxxx                  ",
   "  xx    xxxxxxx            x!!!!x                x x!!!!x             xx        ",
   "  x                xxx     xxxxxx        xxxxx   x x!!!!x      xx               ",
   "  x                        x o o o               x xxxxxx           o o   xx    ",
   "  x          xxxx       o  x o o oy    xx        x o   o                        ",
   "  x  @   y   x  x          x f o oy              x f o    y       xxxxx    y    ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!!x                                                                     ",
   "                                      x!!!x                                                                     ",
   "                                      x!!!x                                                                     ",
   "                                        v     x                                                                 ",
   "                                              x                                                                 ",
   "           f           y                      x         x                                                       ",
   "                   xxxxxxxx     xxxxxx        x        x!x                                     f                ",
   "        xxxxxx        x   x!!!!!x             x        xvx                                     y                ",
   "                o     x   x!!!!!x             x                                            xxxxxxxxxx           ",
   "              xxxxx   x   x!!!!!x             x                   xx!!!!!!!!!!!xx               x               ",
   "       o o            x   xxxxxxx          y  x      f              x|xxxx!!!!!xxxxxxx          x               ",
   "      xxxxx           x                   xxxxx                        x  xxxxx  x              x               ",
   "               o o    x                       x    xxxx          xxx   x         xx      xxxxxxxx               ",
   "              xxxxxx  x                       x                        x         x         x                    ",
   "       o o            x                       x           xxxxx        x         xxxxx     x                    ",
   "      xxxxx           x                       x    y                   x         x         x                    ",
   "                      x                       x   xxxx    o  o     x   x         x      xxxx                    ",
   "               xxxxxxxxx       xxxxxxxx       x                    x   x         x         x                    ",
   "              xx       x              x       x          xxxxxx    x   x   xxxxxxxxxx      x                    ",
   "             xx        x       y      x       x xxxx               x   x   x             xxx                    ",
   "     @       x         x     xxxx     x!!!!!!!x          xxxxx     x   x   x               x                    ",
   "    xxx      x         x              x!!!!!!!x                    x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x              x!!!!!!!x     xxx            x     o     x x       xxx                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx      x!!!!!!!xx    x!!!!!!!!!!    x   o   o   x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!    xxxxxxxxxxxxxx xx  o o  xx                  ",
   "!!!!x x!!!!!!x         x!!!!!x  o o o                xx!!!!!!xx !                    xx y f xx                  ",
   "!!!!x x!!!!!!x         x!!!!!x    f                 xx!!!!!!xx  !                     xxxxxxx                   ",
   "!!!!x x!!!!!!x         x!!!!!xx   y   xxxxxxxxxxxxxx!!!!!!xx   !                                                ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                "],
  ["                                                                                                              ",
   "                                   x!!!!!!!!!!!!!!x                   vx                                      ",
   "               oo                  x!!!!!!!!!!!!!!x                                                           ",
   "                                      v|  xxxxxxxxxxxxxxxxxxxxxxxx                                            ",
   "             xxxxxx      f  xxxx          xx                                                                  ",
   "  xxx  o  o                   x     x     x                                f                                  ",
   "  x x xxxxxx            xxx   x    xxx    x                                                                   ",
   "  x                           x    xxx    xxxxxxx                        xxxxx      o                         ",
   "  x           xxxxxx          x           x                xxxxxxx                xxxx                        ",
   "  x    o o                    xx          x                x!!!!!x            oo                              ",
   "  x   xxxxxx                  x           x                xxxvxxx      xxx  xxxxx                            ",
   "  x                           x  o o    x                         xxx    x           xxx                      ",
   "  x           xxxx            xxxxxxxx                                   x!!!x                  x             ",
   "  x                  xxxx     x            f       oo         f      xxx         xxx                          ",
   "  x                        xxxxxxxxxxxxxxx  x    x || x    x    xxyxx             ooo  xxx              f     ",
   "  x      @    y             fx           x!!x    x!!!!x    x!!!!x    xx   xx  =   ooo                         ",
   "  xxxxxxxxxxxxx!!!!!xxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxx!|!xxxxxxxxxxx ",
   "              xxxxxxx                                                                         xxxxx           ",
   "                                                                                                              "],
  ["            xxxx x   x xxxxx xxxxx xxxxx xxxx xxxx            ",
   "            x    x   x x     x     x     x    x               ",
  "             xxxx x   x x     x     xxx   xxxx xxxx            ",
  "   xxx          x x   x x     x     x        x    x            ",
  "   x@x       xxxx xxxxx xxxxx xxxxx xxxxx xxxx xxxx            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
